parameters:
    xdebug.host: "127.0.0.1"
    xdebug.port: 9000
    autoload_path: ~

services:

    debug_session_factory:
        class: JDWil\Unify\Debugger\DebugSessionFactory
        arguments:
            - "%xdebug.host%"
            - "%xdebug.port%"

    file_type_checker:
        class: JDWil\Unify\Parser\FileTypeChecker

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    finder:
        factory: ['Symfony\Component\Finder\Finder', create]

    lexer:
        factory: "lexer_factory:createLexer"
        arguments:
            - "@=service('lexer_definition').create()"
            - "i"

    lexer_data_generator:
        class: Phlexy\LexerDataGenerator

    lexer_definition:
        class: JDWil\Unify\Lexer\LexerDefinition

    lexer_factory:
        class: \Phlexy\LexerFactory\Stateful\UsingCompiledRegex
        arguments:
            - "@lexer_data_generator"

    parser_factory:
        class: JDWil\Unify\Parser\ParserFactory
        arguments:
            - "@file_type_checker"
            - "@lexer"
            - "@pipeline"
            - "%autoload_path%"

    pipeline:
        factory: ['JDWil\Unify\Assertion\PipelineFactory', create]
        arguments:
            - "@finder"

    test_runner_factory:
        class: JDWil\Unify\TestRunner\TestRunnerFactory
        arguments:
            - "@debug_session_factory"
