parameters:
    xdebug.host: "127.0.0.1"
    xdebug.port: 9000
    autoload_path: ~

services:

    debug_session_factory:
        class: JDWil\Unify\TestRunner\PHP\XDebugSessionFactory
        arguments:
            - "%xdebug.host%"
            - "%xdebug.port%"

    file_type_checker:
        class: JDWil\Unify\Parser\FileTypeChecker

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    finder:
        class: Symfony\Component\Finder\Finder

    # Lexers

    lexer_data_generator:
        class: Phlexy\LexerDataGenerator

    lexer_factory:
        class: \Phlexy\LexerFactory\Stateful\UsingCompiledRegex
        arguments:
            - "@lexer_data_generator"

    markdown_lexer:
        factory: "lexer_factory:createLexer"
        arguments:
            - "@=service('markdown_lexer_definition').create()"
            - "is"

    markdown_lexer_definition:
        class: JDWil\Unify\Lexer\MarkdownLexerDefinition

    shell_lexer:
        factory: "lexer_factory:createLexer"
        arguments:
            - "@=service('shell_lexer_definition').create()"
            - 'is'

    shell_lexer_definition:
        class: JDWil\Unify\Lexer\ShellLexerDefinition

    unify_lexer:
        factory: "lexer_factory:createLexer"
        arguments:
            - "@=service('unify_lexer_definition').create()"
            - "i"

    unify_lexer_definition:
        class: JDWil\Unify\Lexer\UnifyLexerDefinition

    # Parser

    parser_factory:
        class: JDWil\Unify\Parser\ParserFactory
        arguments:
            - "@service_container"

    php_assertion_pipeline:
        factory: ['JDWil\Unify\Assertion\PHP\PHPPipelineFactory', create]
        arguments:
            - "@finder"

    test_runner_factory:
        class: JDWil\Unify\TestRunner\TestRunnerFactory
        arguments:
            - "@debug_session_factory"
