parameters:
    xdebug.host: "127.0.0.1"
    xdebug.port: 9000
    autoload_path: ~

services:

    debug_session_factory:
        class: JDWil\Unify\TestRunner\PHP\XDebugSessionFactory
        arguments:
            - "%xdebug.host%"
            - "%xdebug.port%"

    file_type_checker:
        class: JDWil\Unify\Parser\FileTypeChecker

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    finder:
        class: Symfony\Component\Finder\Finder

    # Lexers

    lexer_data_generator:
        class: Phlexy\LexerDataGenerator

    lexer_factory:
        class: \Phlexy\LexerFactory\Stateful\UsingCompiledRegex
        arguments:
            - "@lexer_data_generator"

    markdown_lexer:
        factory: "lexer_factory:createLexer"
        arguments:
            - "@=service('markdown_lexer_definition').create()"
            - "is"

    markdown_lexer_definition:
        class: JDWil\Unify\Lexer\MarkdownLexerDefinition

    shell_lexer:
        factory: "lexer_factory:createLexer"
        arguments:
            - "@=service('shell_lexer_definition').create()"
            - 'is'

    shell_lexer_definition:
        class: JDWil\Unify\Lexer\ShellLexerDefinition

    unify_lexer:
        factory: "lexer_factory:createLexer"
        arguments:
            - "@=service('unify_lexer_definition').create()"
            - "i"

    unify_lexer_definition:
        class: JDWil\Unify\Lexer\UnifyLexerDefinition

    # Parser

    parser_factory:
        class: JDWil\Unify\Parser\ParserFactory
        arguments:
            - "@service_container"

    php_unify_pipeline:
        class: JDWil\Unify\Parser\Unify\PHP\PHPUnifyParserPipeline
        arguments:
            -
                - "@php_assert_contains_only"
                - "@php_assert_array_contains"
                - "@php_assert_array_count"
                - "@php_assert_array_has_key"
                - "@php_assert_empty"
                - "@php_assert_not_empty"
                - "@php_assert_equal"
                - "@php_assert_not_equal"
                - "@php_assert_less_than"
                - "@php_assert_less_than_or_equal"
                - "@php_assert_greater_than"
                - "@php_assert_greater_than_or_equal"
                - "@php_assert_file_exists"
                - "@php_assert_file_not_exists"
                - "@php_assert_property_exists"
                - "@php_assert_property_not_exists"
                - "@php_assert_readable"
                - "@php_assert_not_readable"
                - "@php_assert_writable"
                - "@php_assert_not_writable"
                - "@php_redefine_procedure"

    php_assert_contains_only:
        class: JDWil\Unify\Parser\Unify\PHP\AssertContainsOnlyParser

    php_assert_array_contains:
        class: JDWil\Unify\Parser\Unify\PHP\AssertArrayContainsParser

    php_assert_array_count:
        class: JDWil\Unify\Parser\Unify\PHP\AssertArrayCountParser

    php_assert_array_has_key:
        class: JDWil\Unify\Parser\Unify\PHP\AssertArrayHasKeyParser

    php_assert_empty:
        class: JDWil\Unify\Parser\Unify\PHP\AssertEmptyParser

    php_assert_not_empty:
        class: JDWil\Unify\Parser\Unify\PHP\AssertNotEmptyParser

    php_assert_equal:
        class: JDWil\Unify\Parser\Unify\PHP\AssertEqualParser

    php_assert_not_equal:
        class: JDWil\Unify\Parser\Unify\PHP\AssertNotEqualParser

    php_assert_less_than:
        class: JDWil\Unify\Parser\Unify\PHP\AssertLessThanParser

    php_assert_less_than_or_equal:
        class: JDWil\Unify\Parser\Unify\PHP\AssertLessThanOrEqualParser

    php_assert_greater_than:
        class: JDWil\Unify\Parser\Unify\PHP\AssertGreaterThanParser

    php_assert_greater_than_or_equal:
        class: JDWil\Unify\Parser\Unify\PHP\AssertGreaterThanOrEqualParser

    php_assert_file_exists:
        class: JDWil\Unify\Parser\Unify\PHP\AssertExistsParser

    php_assert_file_not_exists:
        class: JDWil\Unify\Parser\Unify\PHP\AssertNotExistsParser

    php_assert_property_exists:
        class: JDWil\Unify\Parser\Unify\PHP\AssertPropertyExistsParser

    php_assert_property_not_exists:
        class: JDWil\Unify\Parser\Unify\PHP\AssertPropertyNotExistsParser

    php_assert_readable:
        class: JDWil\Unify\Parser\Unify\PHP\AssertReadableParser

    php_assert_not_readable:
        class: JDWil\Unify\Parser\Unify\PHP\AssertNotReadableParser

    php_assert_writable:
        class: JDWil\Unify\Parser\Unify\PHP\AssertWritableParser

    php_assert_not_writable:
        class: JDWil\Unify\Parser\Unify\PHP\AssertNotWritableParser

    php_redefine_procedure:
        class: JDWil\Unify\Parser\Unify\PHP\RedefineProcedureParser

    test_runner_factory:
        class: JDWil\Unify\TestRunner\TestRunnerFactory
        arguments:
            - "@debug_session_factory"
